### ISSUE TITLE
Display Strategy Game on the Web

### ISSUE THREAD

**Issue by gjwubyron** [sopra-fs23-group-18/pocket-party-web#85]

**Comment by Steesch** [comment]
03ebd6f32fad289b9d6eb533aa47707fa9b58446

**Comment by Steesch** [comment]
f114fa676db641dd692e4403e61381eeb166d88f

**Comment by Steesch** [comment]
d45a16f069ce126e713fe55773394a2f583a0a8b

**Comment by Steesch** [comment]
15d6d78cbd1ba46db8b567993fdf14a1ec8bd883

**Comment by Steesch** [comment]
6be1cbc9de5a04820be3a104177af81b87918b29

**Comment by Steesch** [comment]
42727cf61f49db96f348762d961b30cd86289b89

**Comment by Steesch** [comment]
3f871574d844f25fa46f67b99b8f5b4e899bc401
